name    'inkblot/ppp'
version '0.1.1'
source  'git://github.com/inkblot/puppet-ppp'
author  'inkblot'
license 'Apache 2.0'
summary 'PPP server'
description 'A Puppet module which installs pppd and allows control of chap-secrets'
project_page 'https://github.com/inkblot/puppet-ppp'

dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/concat'
